-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "quantity" DROP DEFAULT,
ALTER COLUMN "quantity" SET DATA TYPE TEXT,
ALTER COLUMN "currentPrice" SET DATA TYPE TEXT,
ALTER COLUMN "previousPrice" SET DATA TYPE TEXT;
